export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL;

export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refreshToken: '/auth/refreshToken',
    resetPassword: '/auth/reset-password',
    forgotPassword: '/auth/forgot-password',
    COMPLETE_REGISTRATION: '/auth/completeRegistration',
  },
  otp: {
    SEND: '/otp/sendOtp',
    VERIFY: '/otp/verifyOtp',
    COMPLETE_REGISTRATION: '/otp/completeRegistration',
    RESEND: '/otp/resendOtp',
    VALIDATE: '/otp/validate/:otpId/:code',
    INVALIDATE: '/otp/invalidateOtp',
    CHECK_USER: '/otp/checkUser',
  },
  doctors: {
    list: '/doctors',
    details: (id: string) => `/doctors/${id}`,
    create: '/doctors',
    update: (id: string) => `/doctors/${id}`,
    delete: (id: string) => `/doctors/${id}`,
  },
  specialty: {
    LIST: '/specialty/getAll',
    CREATE_OR_UPDATE: '/specialty/CreateOrUpdate',
    DELETE: '/specialty/Delete',
    GET_ONE: '/specialty/:id',
    GET_FOR_DROPDOWN: '/specialty/GetSpecialtiesForDropdown',
  },
  country: {
    LIST: '/country/getAll',
    CREATE_OR_UPDATE: '/country/CreateOrUpdate',
    DELETE: '/country/Delete',
    GET_ONE: '/country/:id',
    GET_COUNTRY_FOR_DROPDOWN: '/country/getCountryForDropdown',
    GET_PHONE_CODES_DROPDOWN: '/country/getCountryPhoneCodeFoDropdown',
  },
  medicationType: {
    LIST: '/medicationType/getAll',
    CREATE_OR_UPDATE: '/medicationType/CreateOrUpdate',
    DELETE: '/medicationType/Delete',
    GET_ONE: '/medicationType/:id',
    GET_FOR_DROPDOWN: '/medicationType/GetMedicationTypesForDropdown',
  },
  medicine: {
    LIST: '/medicine/getAll',
    CREATE_OR_UPDATE: '/medicine/CreateOrUpdate',
    DELETE: '/medicine/Delete',
    GET_ONE: '/medicine/:id',
  },
  labTestCategory: {
    LIST: '/labTestCategory/getAll',
    CREATE_OR_UPDATE: '/labTestCategory/CreateOrUpdate',
    DELETE: '/labTestCategory/Delete',
    GET_ONE: '/labTestCategory/:id',
    GET_FOR_DROPDOWN: '/labTestCategory/GetLabTestCategoriesForDropdown',
  },
  labTest: {
    LIST: '/labTest/getAll',
    CREATE_OR_UPDATE: '/labTest/CreateOrUpdate',
    DELETE: '/labTest/Delete',
    GET_ONE: '/labTest/:id',
    GET_FOR_DROPDOWN: '/labTest/GetLabTestForDropdown',
  },
  diagnosisCategory: {
    LIST: '/diagnosisCategory/getAll',
    CREATE_OR_UPDATE: '/diagnosisCategory/CreateOrUpdate',
    DELETE: '/diagnosisCategory/Delete',
    GET_ONE: '/diagnosisCategory/:id',
    GET_FOR_DROPDOWN: '/diagnosisCategory/GetDiagnosisCategoriesForDropdown',
  },
  diagnosis: {
    LIST: '/diagnosis/getAll',
    CREATE_OR_UPDATE: '/diagnosis/CreateOrUpdate',
    DELETE: '/diagnosis/Delete',
    GET_ONE: '/diagnosis/:id',
    GET_FOR_DROPDOWN: '/diagnosis/GetDiagnosesForDropdown',
    GET_FOR_TREE: '/diagnosis/GetDiagnosesTree',
  },
  dentalProcedure: {
    LIST: '/dentalProcedure/getAll',
    CREATE_OR_UPDATE: '/dentalProcedure/CreateOrUpdate',
    DELETE: '/dentalProcedure/Delete',
    GET_ONE: '/dentalProcedure/:id',
  },
  CLINICS: {
    LIST: '/clinics',
    CREATE: '/clinics',
    CREATE_OR_UPDATE: '/clinics/CreateOrUpdate',
    UPDATE: '/clinics/:id',
    DELETE: '/clinics/:id',
    GET_ONE: '/clinics/:id',
  },
  PATIENTS: {
    LIST: '/patients',
    CREATE: '/patients',
    UPDATE: '/patients/:id',
    DELETE: '/patients/:id',
    GET_ONE: '/patients/:id',
  },
  city: {
    LIST: '/city/getAll',
    CREATE_OR_UPDATE: '/city/CreateOrUpdate',
    DELETE: '/city/Delete',
    GET_ONE: '/city/:id',
    GET_FOR_DROPDOWN: '/city/getCitiesForDropdown',
  },
  CURRENCY: {
    LIST: '/currency/getAll',
    CREATE_OR_UPDATE: '/currency/createOrUpdate',
    DELETE: '/currency/delete',
    GET_ONE: '/currency/getById',
    GET_FOR_DROPDOWN: '/currency/getCurrenciesForDropdown',
    GET_DEFAULT: '/currency/getDefaultCurrency',
    SET_DEFAULT: '/currency/setDefaultCurrency',
  },
  radiologyTestCategory: {
    LIST: '/radiologyTestCategory/getAll',
    CREATE_OR_UPDATE: '/radiologyTestCategory/CreateOrUpdate',
    DELETE: '/radiologyTestCategory/Delete',
    GET_ONE: '/radiologyTestCategory/:id',
    GET_FOR_DROPDOWN:
      '/radiologyTestCategory/getRadiologyTestCategoryForDropdown',
  },
  radiologyTest: {
    LIST: '/radiologyTest/getAll',
    CREATE_OR_UPDATE: '/radiologyTest/CreateOrUpdate',
    DELETE: '/radiologyTest/Delete',
    GET_ONE: '/radiologyTest/:id',
    GET_FOR_DROPDOWN: '/radiologyTest/GetRadiologyTestsForDropdown',
  },
  clinicType: {
    LIST: '/clinicType/getAll',
    CREATE_OR_UPDATE: '/clinicType/CreateOrUpdate',
    DELETE: '/clinicType/Delete',
    GET_ONE: '/clinicType/:id',
    GET_FOR_DROPDOWN: '/clinicType/getClinicTypesForDropdown',
  },
  CLINIC: {
    LIST: '/clinic/getAll',
    CREATE_OR_UPDATE: '/clinic/createOrUpdate',
    GET_FOR_EDIT: '/clinic/getClinicForEdit',
    DELETE: '/clinic/delete',
    GET_ONE: '/clinic/getById',
    GET_FOR_DROPDOWN: '/clinic/getClinicsForDropdown',
    GET_SPECIALTIES_FOR_DROPDOWN: '/clinic/getClinicSpecialtiesForDropdown',
    UPLOAD_IMAGE: '/clinic/uploadImage',
    UPDATE_STATUS: '/clinic/updateStatus',
    UPDATE_LOCATION: '/clinic/updateLocation',
    UpdateUserInf: '/clinic/UpdateUserInf',
  },
  CLINIC_STAFF: {
    LIST: '/clinicStaff/getAll',
    CREATE_OR_UPDATE: '/clinicStaff/createOrUpdate',
    GET_BY_ID: '/clinicStaff/GetById',
    GET_ONE: '/clinicStaff/:id',
    GET_FOR_EDIT: '/clinicStaff/getClinicStaffForEdit',
    GET_FOR_DROPDOWN: '/clinicStaff/getClinicStaffForDropdown',
    DELETE: '/clinicStaff/delete',
    UPDATE_STATUS: '/clinicStaff/updateStatus',
    CHANGE_PASSWORD: '/clinicStaff/changeStaffPassword',
  },
  CLINIC_STAFF_LEAVES: {
    LIST: '/clinicStaffLeave/getAll',
    CREATE_OR_UPDATE: '/clinicStaffLeave/createOrUpdate',
    GET_ONE: '/clinicStaffLeave/:id',
    GET_FOR_EDIT: '/clinicStaffLeave/getClinicStaffLeaveForEdit',
    DELETE: '/clinicStaffLeave/delete',
    UPDATE_STATUS: '/clinicStaffLeave/updateStatus',
  },
  CLINIC_PATIENTS: {
    LIST: '/patient/getAll',
    GET_ONE: '/patient/:id',
    GET_FOR_EDIT: '/patient/getPatientForEdit',
    GET_FOR_VIEW: '/patient/getPatientForView',
    GET_PATIENT_DROPDOWN: '/patient/getPatientDropdown',
    CREATE_OR_UPDATE: '/patient/createOrUpdate',
    DELETE: '/patient/Delete',
    UPDATE_STATUS: '/patient/updateStatus',
    GET_PROFILE: `/patient/getPatientProfile`,
    CREATE_OR_UPDATE_CONDITION: '/patient/createOrUpdateMedicalCondition',
    CREATE_OR_UPDATE_ALLERGY: '/patient/createOrUpdateAllergy',
    CREATE_OR_UPDATE_FAMILY_HISTORY: '/patient/createOrUpdateFamilyHistory',

    // New Patient Portal Profile endpoints
    GET_PORTAL_PROFILE: '/patient/getPatientPortalProfile',
    UPDATE_PORTAL_PROFILE: '/patient/updatePatientPortalProfile',
    GET_HEALTH_METRICS: '/patient/getPatientHealthMetrics',
    UPDATE_HEALTH_METRICS: '/patient/updatePatientHealthMetrics',
    CREATE_OR_UPDATE_EMERGENCY_CONTACT:
      '/patient/createOrUpdateEmergencyContact',
    DELETE_EMERGENCY_CONTACT: '/patient/deleteEmergencyContact',

    // New Patient Portal Dashboard, Appointments, Visits, and Prescriptions endpoints
    GET_PORTAL_DASHBOARD: '/patient/getPatientPortalDashboard',
    GET_PATIENT_APPOINTMENTS: '/patient/getPatientAppointments',
    UPDATE_PATIENT_APPOINTMENT: '/patient/updatePatientAppointment',
    GET_PATIENT_VISITS: '/patient/getPatientVisits',
    UPDATE_PATIENT_PRESCRIPTION: '/patient/updatePatientPrescription',
    SAVE_APPOINTMENT: '/patient/savePatientAppointments',
    GET_APPOINTMENT_DETAILS: '/patient/getPatientAppointmentDetails',
    BOOK_FOLLOW_UP_APPOINTMENT: '/patient/bookFollowUpAppointment',
    GET_VISIT_DETAILS: '/patient/getPatientVisitDetails',
  },
  APPOINTMENT: {
    LIST: '/appointment/getAll',
    GET_ONE: '/appointment/getById',
    GET_FOR_EDIT: '/appointment/getAppointmentForEdit',
    CREATE_OR_UPDATE: '/appointment/createOrUpdate',
    DELETE: '/appointment/delete',
    UPDATE_STATUS: '/appointment/updateStatus',
  },
  VISIT_ENDPOINTS: {
    LIST: '/visit/getAll',
    GET_ONE: '/visit/getById',
    GET_FOR_EDIT: '/visit/getVisitForEdit',
    CREATE_OR_UPDATE: '/visit/createOrUpdate',
    DELETE: '/visit/delete',
    UPDATE_STATUS: '/visit/:id/status',
    GET_STATUS_HISTORY: '/visit/:id/statusHistory',
    GET_DIAGNOSES: '/visit/:id/diagnoses',
    GET_PRESCRIPTIONS: '/visit/:id/prescriptions',
    GET_LAB_TESTS: '/visit/:id/labTests',
    GET_RADIOLOGY_TESTS: '/visit/:id/radiologyTests',
    GET_DENTAL_PROCEDURES: '/visit/:id/dentalProcedures',
  },
  visitLabTest: {
    LIST: '/visitLabTest/getAll',
    CREATE_OR_UPDATE: '/visitLabTest/CreateOrUpdate',
    DELETE: '/visitLabTest/Delete',
    GET_ONE: '/visitLabTest/:id',
    GET_BY_VISIT_ID: '/visitLabTest/getByVisitId',
    GET_BY_LAB_TEST_ID: '/visitLabTest/getByLabTestId',
    GET_VISITS_WITH_LAB_TESTS: '/visitLabTest/getVisitsWithLabTests',
    GET_SUMMARY: '/visitLabTest/getSummary',
    UPDATE_STATUS: '/visitLabTest/updateStatus',
    UPDATE_RESULT: '/visitLabTest/updateResult',
    PATIENT_LAB_TESTS: '/visitLabTest/getPatientLabTests',
    PATIENT_LAB_TEST_DETAILS: '/visitLabTest/getPatientLabTestDetails',
  },
  visitRadiologyTest: {
    LIST: '/visitRadiologyTest/getAll',
    CREATE_OR_UPDATE: '/visitRadiologyTest/CreateOrUpdate',
    DELETE: '/visitRadiologyTest/Delete',
    GET_ONE: '/visitRadiologyTest/:id',
    GET_BY_VISIT_ID: '/visitRadiologyTest/getByVisitId',
    GET_BY_RADIOLOGY_TEST_ID: '/visitRadiologyTest/getByRadiologyTestId',
    GET_VISITS_WITH_RADIOLOGY_TESTS:
      '/visitRadiologyTest/getVisitsWithRadiologyTests',
    GET_SUMMARY: '/visitRadiologyTest/getSummary',
    UPDATE_STATUS: '/visitRadiologyTest/updateStatus',
    UPDATE_RESULT: '/visitRadiologyTest/updateResult',
    PATIENT_RADIOLOGY_TESTS: '/visitRadiologyTest/getPatientRadiologyTests',
    PATIENT_RADIOLOGY_TEST_DETAILS:
      '/visitRadiologyTest/getPatientRadiologyTestDetails',
  },
  visitPrescription: {
    LIST: '/visitPrescription/getAll',
    CREATE_OR_UPDATE: '/visitPrescription/CreateOrUpdate',
    DELETE: '/visitPrescription/Delete',
    GET_ONE: '/visitPrescription/:id',
    GET_BY_VISIT_ID: '/visitPrescription/getByVisitId',
    UPDATE_STATUS: '/visitPrescription/updateStatus',
    DISPENSE_MEDICINE: '/visitPrescription/dispenseMedicine',
    PATIENT_PORTAL_PRESCRIPTIONS:
      '/visitPrescription/getPatientPortalPrescriptions',
    GET_PRESCRIBED_MEDICATIONS:
      '/visitPrescription/getPrescribedMedicationsByVisitId',
  },
  FINANCE_ENDPOINTS: {
    REVENUES: {
      GET_LIST: '/clinicRevenue/getAll',
      GET_ONE: '/clinicRevenue/getById',
      CREATE_OR_UPDATE: '/clinicRevenue/createOrUpdate',
      DELETE: '/clinicRevenue/delete',
      GET_SUMMARY: '/clinicRevenue/getSummary',
      GET_DASHBOARD_STATS: '/clinicRevenue/getDashboardStats',
    },
    EXPENSES: {
      GET_LIST: '/clinicExpense/getAll',
      GET_ONE: '/clinicExpense/getById',
      CREATE_OR_UPDATE: '/clinicExpense/createOrUpdate',
      DELETE: '/clinicExpense/delete',
      GET_SUMMARY: '/clinicExpense/getSummary',
      GET_DASHBOARD_STATS: '/clinicExpense/getDashboardStats',
    },
    SALARIES: {
      GET_LIST: '/staffSalary/getAll',
      GET_ONE: '/staffSalary/getById',
      CREATE_OR_UPDATE: '/staffSalary/createOrUpdate',
      DELETE: '/staffSalary/delete',
      GET_SUMMARY: '/staffSalary/getSummary',
    },
    TRANSACTIONS: {
      GET_LIST: '/clinicTransaction/getAll',
      GET_ONE: '/clinicTransaction/getById',
      CREATE_OR_UPDATE: '/clinicTransaction/createOrUpdate',
      DELETE: '/clinicTransaction/delete',
      GET_SUMMARY: '/clinicTransaction/getSummary',
      GET_DASHBOARD_STATS: '/clinicTransaction/getDashboardStats',
    },
    SERVICE_PRICES: {
      GET_LIST: '/servicePrice/getAll',
      GET_ONE: '/servicePrice/getById',
      GET_SUMMARY: '/servicePrice/getSummary',
      CREATE_OR_UPDATE: '/servicePrice/createOrUpdate',
      DELETE: '/servicePrice/delete',
    },
    SERVICES_BY_TYPE: '/servicePrice/getServicePriceByType',
    INVOICES: {
      GET_LIST: '/invoice/getAll',
      GET_ONE: '/invoice/getById',
      CREATE_OR_UPDATE: '/invoice/createOrUpdate',
      DELETE: '/invoice/delete',
      GET_SUMMARY: '/invoice/getSummary',
      GET_DASHBOARD_STATS: '/invoice/getDashboardStats',
      ADD_PAYMENT: '/invoice/addPayment',
    },
  },
  ROLE: {
    GET_LIST: '/role/getRoles',
    GET_ONE: '/role/getRole',
    CREATE: '/role/createOrUpdate',
    UPDATE: '/role/createOrUpdate',
    DELETE: '/role/delete',
    UPDATE_PERMISSIONS: '/role/updatePermissions',
  },
  USER_ROLE: {
    GET_USER_ROLES: '/role/getUserRoles',
    UPDATE_USER_ROLES: '/role/updateUserRoles',
    GET_USER_PERMISSIONS: '/role/getUserPermissions',
    END_SESSION: '/role/endUserSession',
  },
  PERMISSION: {
    GET_USER_PERMISSION_SELECTION: '/userPermission/getUserPermissionSelection',
    SAVE_USER_PERMISSIONS: '/userPermission/saveUserPermissions',
  },
  ATTACHMENT: {
    GET_BY_ID: '/attachment/getById/:id',
    GET_BY_ENTITY: '/attachment/getByEntity',
    UPLOAD: '/attachment/upload',
    UPLOAD_MULTIPLE: '/attachment/uploadMultiple',
    DELETE: '/attachment/delete',
    DOWNLOAD: '/attachment/download',
    GET_URL: '/attachment/getUrl',
    UPLOAD_TEMP: '/api/attachment/upload-temp',
    CONVERT_TEMP: '/api/attachment/convert-temp',
    GET_TEMP_BY_SESSION: '/api/attachment/temp/:sessionId',
    CLEANUP_TEMP: '/api/attachment/cleanup-temp',
  },
  CLINIC_BOOKING_CONDITION: {
    LIST: '/clinicBookingCondition/getAll',
    CREATE_OR_UPDATE: '/clinicBookingCondition/createOrUpdate',
    DELETE: '/clinicBookingCondition/delete',
    GET_ONE: '/clinicBookingCondition/getById',
    GET_FOR_DROPDOWN: '/clinicBookingCondition/getForDropdown',
    GET_BY_CLINIC_ID: '/clinicBookingCondition/getByClinicId',
    GET_FOR_EDIT: '/clinicBookingCondition/getForEdit',
    UPDATE_STATUS: '/clinicBookingCondition/updateStatus',
  },
  CLINIC_SETTINGS: {
    GET: '/clinicSettings/GetClinicSettings',
    SAVE: '/clinicSettings/SaveClinicSettings',
  },
} as const;
