export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL;

export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refreshToken: '/auth/refreshToken',
    resetPassword: '/auth/reset-password',
    forgotPassword: '/auth/forgot-password',
  },
  doctors: {
    list: '/doctors',
    details: (id: string) => `/doctors/${id}`,
    create: '/doctors',
    update: (id: string) => `/doctors/${id}`,
    delete: (id: string) => `/doctors/${id}`,
  },
  specialty: {
    LIST: '/specialty/getAll',
    CREATE_OR_UPDATE: '/specialty/CreateOrUpdate',
    DELETE: '/specialty/Delete',
    GET_ONE: '/specialty/:id',
    GET_FOR_DROPDOWN: '/specialty/GetSpecialtiesForDropdown',
  },
  country: {
    LIST: '/country/getAll',
    CREATE_OR_UPDATE: '/country/CreateOrUpdate',
    DELETE: '/country/Delete',
    GET_ONE: '/country/:id',
    GET_COUNTRY_FOR_DROPDOWN: '/country/getCountryForDropdown',
  },
  medicationType: {
    LIST: '/medicationType/getAll',
    CREATE_OR_UPDATE: '/medicationType/CreateOrUpdate',
    DELETE: '/medicationType/Delete',
    GET_ONE: '/medicationType/:id',
    GET_FOR_DROPDOWN: '/medicationType/GetMedicationTypesForDropdown',
  },
  medicine: {
    LIST: '/medicine/getAll',
    CREATE_OR_UPDATE: '/medicine/CreateOrUpdate',
    DELETE: '/medicine/Delete',
    GET_ONE: '/medicine/:id',
  },
  labTestCategory: {
    LIST: '/labTestCategory/getAll',
    CREATE_OR_UPDATE: '/labTestCategory/CreateOrUpdate',
    DELETE: '/labTestCategory/Delete',
    GET_ONE: '/labTestCategory/:id',
    GET_FOR_DROPDOWN: '/labTestCategory/GetLabTestCategoriesForDropdown',
  },
  labTest: {
    LIST: '/labTest/getAll',
    CREATE_OR_UPDATE: '/labTest/CreateOrUpdate',
    DELETE: '/labTest/Delete',
    GET_ONE: '/labTest/:id',
  },
  diagnosisCategory: {
    LIST: '/diagnosisCategory/getAll',
    CREATE_OR_UPDATE: '/diagnosisCategory/CreateOrUpdate',
    DELETE: '/diagnosisCategory/Delete',
    GET_ONE: '/diagnosisCategory/:id',
    GET_FOR_DROPDOWN: '/diagnosisCategory/GetDiagnosisCategoriesForDropdown',
  },
  diagnosis: {
    LIST: '/diagnosis/getAll',
    CREATE_OR_UPDATE: '/diagnosis/CreateOrUpdate',
    DELETE: '/diagnosis/Delete',
    GET_ONE: '/diagnosis/:id',
  },
  dentalProcedure: {
    LIST: '/dentalProcedure/getAll',
    CREATE_OR_UPDATE: '/dentalProcedure/CreateOrUpdate',
    DELETE: '/dentalProcedure/Delete',
    GET_ONE: '/dentalProcedure/:id',
  },
  CLINICS: {
    LIST: '/clinics',
    CREATE: '/clinics',
    UPDATE: '/clinics/:id',
    DELETE: '/clinics/:id',
    GET_ONE: '/clinics/:id',
  },
  PATIENTS: {
    LIST: '/patients',
    CREATE: '/patients',
    UPDATE: '/patients/:id',
    DELETE: '/patients/:id',
    GET_ONE: '/patients/:id',
  },
  city: {
    LIST: '/city/getAll',
    CREATE_OR_UPDATE: '/city/CreateOrUpdate',
    DELETE: '/city/Delete',
    GET_ONE: '/city/:id',
    GET_FOR_DROPDOWN: '/city/getCitiesForDropdown',
  },
  radiologyTestCategory: {
    LIST: '/radiologyTestCategory/getAll',
    CREATE_OR_UPDATE: '/radiologyTestCategory/CreateOrUpdate',
    DELETE: '/radiologyTestCategory/Delete',
    GET_ONE: '/radiologyTestCategory/:id',
    GET_FOR_DROPDOWN:
      '/radiologyTestCategory/getRadiologyTestCategoryForDropdown',
  },
  radiologyTest: {
    LIST: '/radiologyTest/getAll',
    CREATE_OR_UPDATE: '/radiologyTest/CreateOrUpdate',
    DELETE: '/radiologyTest/Delete',
    GET_ONE: '/radiologyTest/:id',
    GET_FOR_DROPDOWN: '/radiologyTest/getRadiologyTestForDropdown',
  },
  clinicType: {
    LIST: '/clinicType/getAll',
    CREATE_OR_UPDATE: '/clinicType/CreateOrUpdate',
    DELETE: '/clinicType/Delete',
    GET_ONE: '/clinicType/:id',
    GET_FOR_DROPDOWN: '/clinicType/getClinicTypesForDropdown',
  },
  CLINIC: {
    LIST: '/clinic/getAll',
    CREATE_OR_UPDATE: '/clinic/createOrUpdate',
    DELETE: '/clinic/delete',
    GET_ONE: '/clinic',
    GET_FOR_DROPDOWN: '/clinic/GetClinicsForDropdown',
    UPLOAD_IMAGE: '/clinic/uploadImage',
    UPDATE_STATUS: '/clinic/updateStatus',
    UPDATE_LOCATION: '/clinic/updateLocation',
  },
  // Add more endpoints as needed
} as const;
