import { CalendarCheck, Stethoscope, FilePlus2, User } from 'lucide-react';
import {
  QuickAction,
  Appointment,
  Medication,
  Visit,
  Notification,
  HealthAlert,
  HealthMetrics,
} from './types';

export const quickActions: QuickAction[] = [
  {
    id: 'action-1',
    titleKey: 'patientPortal.quickActions.bookAppointment',
    icon: CalendarCheck,
    url: '/patient-portal/appointments/book',
    color: 'blue',
  },
  {
    id: 'action-2',
    titleKey: 'patientPortal.quickActions.requestConsultation',
    icon: Stethoscope,
    url: '/patient-portal/telemedicine',
    color: 'purple',
  },
  {
    id: 'action-3',
    titleKey: 'patientPortal.quickActions.requestPrescription',
    icon: FilePlus2,
    url: '/patient-portal/prescriptions/request',
    color: 'green',
  },
  {
    id: 'action-4',
    titleKey: 'patientPortal.quickActions.profile',
    icon: User,
    url: '/patient-portal/profile',
    color: 'amber',
  },
];

export const upcomingAppointments: Appointment[] = [
  {
    id: 'app-1',
    doctorName: 'د. أحمد محمد',
    doctorAvatar: '/avatars/doctor-1.png',
    specialty: 'طب عام',
    clinic: 'العيادة الرئيسية',
    date: '2025-08-10',
    time: '10:00',
    status: 'confirmed',
    type: 'checkup',
    notes: 'فحص دوري',
  },
  {
    id: 'app-2',
    doctorName: 'د. سارة خالد',
    doctorAvatar: '/avatars/doctor-2.png',
    specialty: 'أسنان',
    clinic: 'عيادة الأسنان',
    date: '2025-08-15',
    time: '14:30',
    status: 'confirmed',
    type: 'treatment',
    notes: 'متابعة علاج الأسنان',
  },
  {
    id: 'app-3',
    doctorName: 'د. محمود عبدالله',
    doctorAvatar: '/avatars/doctor-3.png',
    specialty: 'جلدية',
    clinic: 'عيادة الجلدية',
    date: '2025-08-20',
    time: '11:15',
    status: 'pending',
    type: 'consultation',
    notes: 'استشارة جلدية',
  },
];

export const activeMedications: Medication[] = [
  {
    id: 'med-1',
    name: 'باراسيتامول',
    image: '/medications/paracetamol.png',
    dosage: '500 مجم',
    frequency: 'كل 6 ساعات',
    remainingDays: 5,
    totalDays: 7,
    startDate: '2025-08-01',
    endDate: '2025-08-07',
    instructions: 'يؤخذ بعد الطعام',
    prescribedBy: 'د. محمد علي',
    refillable: true,
    priority: 'high',
  },
  {
    id: 'med-2',
    name: 'أموكسيسيلين',
    image: '/medications/amoxicillin.png',
    dosage: '250 مجم',
    frequency: 'مرتين يومياً',
    remainingDays: 3,
    totalDays: 10,
    startDate: '2025-07-28',
    endDate: '2025-08-07',
    instructions: 'يؤخذ قبل الطعام بساعة',
    prescribedBy: 'د. محمد علي',
    refillable: false,
    priority: 'medium',
  },
  {
    id: 'med-3',
    name: 'لوراتادين',
    image: '/medications/loratadine.png',
    dosage: '10 مجم',
    frequency: 'مرة واحدة يومياً',
    remainingDays: 10,
    totalDays: 14,
    startDate: '2025-08-02',
    endDate: '2025-08-16',
    instructions: 'يؤخذ في الصباح',
    prescribedBy: 'د. فاطمة أحمد',
    refillable: true,
    priority: 'low',
  },
];

export const recentVisits: Visit[] = [
  {
    id: 'visit-1',
    doctorName: 'د. محمد علي',
    doctorAvatar: '/avatars/doctor-4.png',
    specialty: 'طب عام',
    clinic: 'العيادة الرئيسية',
    date: '2025-07-25',
    diagnosis: 'التهاب الحلق',
    treatment: 'مضادات حيوية + مسكنات',
    followUp: true,
    followUpDate: '2025-08-10',
    documents: 3,
    tests: 2,
  },
  {
    id: 'visit-2',
    doctorName: 'د. فاطمة أحمد',
    doctorAvatar: '/avatars/doctor-5.png',
    specialty: 'جلدية',
    clinic: 'عيادة الجلدية',
    date: '2025-07-15',
    diagnosis: 'حساسية جلدية',
    treatment: 'كريم موضعي + مضادات الهيستامين',
    followUp: false,
    documents: 1,
    tests: 0,
  },
  {
    id: 'visit-3',
    doctorName: 'د. خالد محمود',
    doctorAvatar: '/avatars/doctor-6.png',
    specialty: 'عظام',
    clinic: 'عيادة العظام',
    date: '2025-07-05',
    diagnosis: 'التهاب المفاصل',
    treatment: 'مسكنات + علاج طبيعي',
    followUp: true,
    followUpDate: '2025-08-05',
    documents: 2,
    tests: 1,
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    title: 'تم تأكيد موعدك',
    message:
      'تم تأكيد موعدك مع د. أحمد خالد يوم الأحد، 15 أكتوبر الساعة 10:00 صباحاً',
    type: 'appointment',
    time: '30 دقيقة',
    read: false,
    timestamp: new Date(2023, 9, 15, 9, 30),
    actionUrl: '/patient-portal/appointments/123',
    actionText: 'عرض الموعد',
  },
  {
    id: '2',
    title: 'نتائج التحاليل جاهزة',
    message: 'نتائج تحاليل الدم الخاصة بك جاهزة للاطلاع عليها',
    type: 'test',
    time: '3 ساعات',
    read: true,
    timestamp: new Date(2023, 9, 15, 7, 0),
    actionUrl: '/patient-portal/tests/456',
    actionText: 'عرض النتائج',
  },
  {
    id: '3',
    title: 'تذكير بموعد الدواء',
    message: 'تذكير بموعد تناول دواء الضغط (أملوديبين) الساعة 9:00 مساءً',
    type: 'medication',
    time: '12 ساعة',
    read: false,
    timestamp: new Date(2023, 9, 14, 21, 0),
    actionUrl: '/patient-portal/medications',
    actionText: 'عرض الأدوية',
  },
  {
    id: '4',
    title: 'رسالة جديدة من الطبيب',
    message: 'لديك رسالة جديدة من د. سارة محمد بخصوص استفسارك الأخير',
    type: 'message',
    time: '1 يوم',
    read: true,
    timestamp: new Date(2023, 9, 14, 14, 30),
    actionUrl: '/patient-portal/messages/789',
    actionText: 'قراءة الرسالة',
  },
  {
    id: '5',
    title: 'تحديث في نظام المواعيد',
    message:
      'تم تحديث نظام حجز المواعيد، يمكنك الآن حجز المواعيد عبر تطبيق الهاتف',
    type: 'system',
    time: '2 يوم',
    read: true,
    timestamp: new Date(2023, 9, 13, 10, 0),
    actionUrl: null,
    actionText: null,
  },
];

export const healthAlerts: HealthAlert[] = [
  {
    id: '1',
    title: 'ارتفاع في ضغط الدم',
    message:
      'تم تسجيل قراءات مرتفعة لضغط الدم في آخر 3 قياسات. يرجى مراجعة طبيبك.',
    priority: 'high',
    actionUrl: '/patient-portal/appointments/new',
    actionText: 'حجز موعد مع الطبيب',
  },
  {
    id: '2',
    title: 'تذكير بموعد التطعيم',
    message:
      'حان موعد التطعيم السنوي ضد الإنفلونزا. يرجى حجز موعد في أقرب وقت ممكن.',
    priority: 'medium',
    actionUrl: '/patient-portal/vaccinations',
    actionText: 'حجز موعد التطعيم',
  },
  {
    id: '3',
    title: 'تحديث معلومات الصحة',
    message:
      'لم يتم تحديث قياسات الوزن منذ أكثر من 3 أشهر. يرجى تحديث بياناتك الصحية.',
    priority: 'low',
    actionUrl: '/patient-portal/health-metrics/update',
    actionText: 'تحديث البيانات',
  },
];

export const healthMetrics: HealthMetrics = {
  bloodPressure: {
    systolic: 125,
    diastolic: 82,
    status: 'normal',
    lastUpdated: new Date(2023, 9, 10).toISOString(),
    history: [
      { systolic: 125, diastolic: 82, date: new Date(2023, 9, 10) },
      { systolic: 128, diastolic: 84, date: new Date(2023, 9, 3) },
      { systolic: 130, diastolic: 85, date: new Date(2023, 8, 27) },
    ],
  },
  bloodSugar: {
    value: 95,
    unit: 'mg/dL',
    status: 'normal',
    lastUpdated: new Date(2023, 9, 12).toISOString(),
    history: [
      { value: 95, date: new Date(2023, 9, 12) },
      { value: 98, date: new Date(2023, 9, 5) },
      { value: 100, date: new Date(2023, 8, 29) },
    ],
  },
  weight: {
    value: 75,
    unit: 'كجم',
    trend: 'stable',
    lastUpdated: new Date(2023, 9, 8).toISOString(),
    history: [
      { value: 75, date: new Date(2023, 9, 8) },
      { value: 75.5, date: new Date(2023, 8, 24) },
      { value: 76, date: new Date(2023, 8, 10) },
    ],
  },
  heartRate: {
    value: 72,
    unit: 'نبضة/دقيقة',
    status: 'normal',
    lastUpdated: new Date(2023, 9, 11).toISOString(),
    history: [
      { value: 72, date: new Date(2023, 9, 11) },
      { value: 75, date: new Date(2023, 9, 4) },
      { value: 70, date: new Date(2023, 8, 28) },
    ],
  },
  cholesterol: {
    total: 180,
    hdl: 60,
    ldl: 100,
    unit: 'mg/dL',
    status: 'normal',
    lastUpdated: new Date(2023, 8, 15).toISOString(),
  },
};
