import { Appointment } from './types';

export const mockAppointments: Appointment[] = [
  {
    id: 'app-1',
    doctorName: 'د. أحمد محمد',
    specialty: 'طب عام',
    clinicName: 'عيادة الطب العام',
    date: '2025-08-10',
    time: '10:00',
    status: 'confirmed',
    notes: 'فحص دوري',
    createdAt: '2025-07-30',
  },
  {
    id: 'app-2',
    doctorName: 'د. سارة خالد',
    specialty: 'أسنان',
    clinicName: 'عيادة الأسنان',
    date: '2025-08-15',
    time: '14:30',
    status: 'confirmed',
    notes: 'تنظيف أسنان',
    createdAt: '2025-08-01',
  },
  {
    id: 'app-3',
    doctorName: 'د. محمد علي',
    specialty: 'جلدية',
    clinicName: 'عيادة الجلدية',
    date: '2025-07-25',
    time: '09:15',
    status: 'completed',
    notes: 'فحص حساسية جلدية',
    createdAt: '2025-07-15',
  },
  {
    id: 'app-4',
    doctorName: 'د. فاطمة أحمد',
    specialty: 'عيون',
    clinicName: 'عيادة العيون',
    date: '2025-07-20',
    time: '11:30',
    status: 'cancelled',
    notes: 'فحص نظر',
    createdAt: '2025-07-10',
  },
  {
    id: 'app-5',
    doctorName: 'د. خالد محمود',
    specialty: 'باطنية',
    clinicName: 'عيادة الباطنية',
    date: '2025-08-20',
    time: '13:00',
    status: 'confirmed',
    notes: 'متابعة حالة',
    createdAt: '2025-08-02',
  },
];
