import {
  ChartBarIcon,
  UserGroupIcon,
  ClipboardDocumentListIcon,
  CalendarIcon,
  UserIcon,
  HomeIcon,
  ListBulletIcon,
  AcademicCapIcon,
  GlobeAltIcon,
  MapPinIcon,
  BuildingOfficeIcon,
  ArchiveBoxIcon,
  BoltIcon,
  BookmarkIcon,
  HeartIcon,
  PuzzlePieceIcon,
  ShieldCheckIcon,
  DocumentTextIcon,
  ClipboardDocumentCheckIcon,
  SparklesIcon,
  Cog6ToothIcon,
  BanknotesIcon,
  CurrencyDollarIcon,
  ReceiptPercentIcon,
  DocumentDuplicateIcon,
  ArrowTrendingUpIcon,
  UsersIcon,
  ArrowsRightLeftIcon,
} from '@heroicons/react/24/outline';

import type { NavItem } from '@/types/navigation';
import { PermissionKeys } from './permissions';

export const doctorNav: NavItem[] = [
  {
    name: 'navigation.doctor.dashboard',
    id: 'doctor-dashboard',
    href: '/clinic/doctor/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_DOCTOR_DASHBOARD,
  },
  {
    name: 'navigation.doctor.visits',
    id: 'doctor-visits',
    href: '/clinic/doctor/visits',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.MANAGE_VISITS,
  },
  {
    name: 'navigation.doctor.leaves',
    id: 'doctor-leaves',
    href: '/clinic/doctor/leaves',
    icon: CalendarIcon,
    permission: PermissionKeys.MANAGE_LEAVES,
  },
  {
    name: 'navigation.doctor.profile',
    id: 'doctor-profile',
    href: '/clinic/doctor/profile',
    icon: UserIcon,
    permission: PermissionKeys.VIEW_PROFILE,
  },
];

export const adminNav: NavItem[] = [
  {
    name: 'navigation.admin.dashboard',
    id: 'admin-dashboard',
    href: '/clinic/admin/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_ADMIN_DASHBOARD,
  },
  {
    name: 'navigation.admin.clinics.title',
    id: 'admin-clinics',
    icon: HomeIcon,
    permission: PermissionKeys.MANAGE_CLINICS,
    children: [
      {
        name: 'navigation.admin.clinics.management.title',
        id: 'admin-clinics-management',
        icon: ClipboardDocumentListIcon,
        permission: PermissionKeys.MANAGE_CLINICS,
        children: [
          {
            name: 'navigation.admin.clinics.management.list',
            id: 'admin-clinics-list',
            href: '/admin/clinics',
            icon: ClipboardDocumentListIcon,
            permission: PermissionKeys.VIEW_CLINICS,
          },
          {
            name: 'navigation.admin.clinics.management.add',
            id: 'admin-clinics-add',
            href: '/admin/clinics/add',
            icon: UserGroupIcon,
            permission: PermissionKeys.CREATE_CLINICS,
          },
        ],
      },
      {
        name: 'navigation.admin.clinics.reports.title',
        id: 'admin-clinics-reports',
        icon: ChartBarIcon,
        permission: PermissionKeys.VIEW_REPORTS,
        children: [
          {
            name: 'navigation.admin.clinics.reports.performance',
            id: 'admin-clinics-reports-performance',
            href: '/admin/clinics/reports/performance',
            icon: ChartBarIcon,
            permission: PermissionKeys.VIEW_PERFORMANCE_REPORTS,
          },
          {
            name: 'navigation.admin.clinics.reports.analytics',
            id: 'admin-clinics-reports-analytics',
            href: '/admin/clinics/reports/analytics',
            icon: ChartBarIcon,
            permission: PermissionKeys.VIEW_ANALYTICS_REPORTS,
          },
        ],
      },
    ],
  },
  {
    name: 'navigation.admin.lookups.title',
    id: 'admin-lookups',
    icon: ListBulletIcon,
    permission: PermissionKeys.MANAGE_LOOKUPS,
    children: [
      {
        name: 'navigation.admin.lookups.specialty',
        id: 'admin-lookups-specialty',
        href: '/admin/lookups/specialty',
        icon: AcademicCapIcon,
        permission: PermissionKeys.VIEW_SPECIALTY,
      },
      {
        name: 'navigation.admin.lookups.country',
        id: 'admin-lookups-country',
        href: '/admin/lookups/country',
        icon: GlobeAltIcon,
        permission: PermissionKeys.VIEW_COUNTRY,
      },
      {
        name: 'navigation.admin.lookups.city',
        id: 'admin-lookups-city',
        href: '/admin/lookups/city',
        icon: MapPinIcon,
        permission: PermissionKeys.VIEW_CITY,
      },
      {
        name: 'navigation.admin.lookups.clinicType',
        id: 'admin-lookups-clinic-type',
        href: '/admin/lookups/clinic-type',
        icon: BuildingOfficeIcon,
        permission: PermissionKeys.VIEW_CLINIC_TYPE,
      },
      {
        name: 'navigation.admin.lookups.currency',
        id: 'admin-lookups-currency',
        href: '/admin/lookups/currency',
        icon: CurrencyDollarIcon,
        permission: PermissionKeys.VIEW_CURRENCY,
      },
      {
        name: 'navigation.admin.lookups.radiologyTestCategory',
        id: 'admin-lookups-radiology-test-category',
        href: '/admin/lookups/radiology-test-category',
        icon: ArchiveBoxIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY_TEST_CATEGORY,
      },
      {
        name: 'navigation.admin.lookups.radiologyTest',
        id: 'admin-lookups-radiology-test',
        href: '/admin/lookups/radiology-test',
        icon: BoltIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY_TEST,
      },
      {
        name: 'navigation.admin.lookups.medicationType',
        id: 'admin-lookups-medication-type',
        href: '/admin/lookups/medication-type',
        icon: BookmarkIcon,
        permission: PermissionKeys.VIEW_MEDICATION_TYPE,
      },
      {
        name: 'navigation.admin.lookups.medicine',
        id: 'admin-lookups-medicine',
        href: '/admin/lookups/medicine',
        icon: HeartIcon,
        permission: PermissionKeys.VIEW_MEDICINE,
      },
      {
        name: 'navigation.admin.lookups.labTestCategory',
        id: 'admin-lookups-lab-test-category',
        href: '/admin/lookups/lab-test-category',
        icon: PuzzlePieceIcon,
        permission: PermissionKeys.VIEW_LAB_TEST_CATEGORY,
      },
      {
        name: 'navigation.admin.lookups.labTest',
        id: 'admin-lookups-lab-test',
        href: '/admin/lookups/lab-test',
        icon: ShieldCheckIcon,
        permission: PermissionKeys.VIEW_LAB_TEST,
      },
      {
        name: 'navigation.admin.lookups.diagnosisCategory',
        id: 'admin-lookups-diagnosis-category',
        href: '/admin/lookups/diagnosis-category',
        icon: DocumentTextIcon,
        permission: PermissionKeys.VIEW_DIAGNOSIS_CATEGORY,
      },
      {
        name: 'navigation.admin.lookups.diagnosis',
        id: 'admin-lookups-diagnosis',
        href: '/admin/lookups/diagnosis',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_DIAGNOSIS,
      },
      {
        name: 'navigation.admin.lookups.dentalProcedure',
        id: 'admin-lookups-dental-procedure',
        href: '/admin/lookups/dental-procedure',
        icon: SparklesIcon,
        permission: PermissionKeys.VIEW_DENTAL_PROCEDURE,
      },
    ],
  },
  {
    name: 'navigation.admin.users',
    id: 'admin-users',
    href: '/admin/users',
    icon: UserGroupIcon,
    permission: PermissionKeys.VIEW_USERS,
  },
];

export const clinicNav: NavItem[] = [
  {
    name: 'navigation.clinic.dashboard',
    id: 'clinic-dashboard',
    href: '/clinic/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_CLINIC_DASHBOARD,
  },
  {
    name: 'navigation.clinic.appointments',
    id: 'clinic-appointments',
    href: '/clinic/appointments',
    icon: CalendarIcon,
    permission: PermissionKeys.VIEW_APPOINTMENTS,
  },
  {
    name: 'navigation.clinic.patients',
    id: 'clinic-patients',
    href: '/clinic/patients',
    icon: UserGroupIcon,
    permission: PermissionKeys.VIEW_PATIENTS,
  },
  {
    name: 'navigation.clinic.staff.title',
    id: 'clinic-staff',
    icon: UserIcon,
    permission: PermissionKeys.VIEW_STAFF,
    children: [
      {
        name: 'navigation.clinic.staff.list',
        id: 'clinic-staff-list',
        href: '/clinic/staff',
        icon: UserGroupIcon,
        permission: PermissionKeys.VIEW_STAFF,
      },
      {
        name: 'navigation.clinic.staff.leaves',
        id: 'clinic-staff-leaves',
        href: '/clinic/staff/leaves',
        icon: CalendarIcon,
        permission: PermissionKeys.MANAGE_LEAVES,
      },
    ],
  },
  {
    name: 'navigation.clinic.laboratory.title',
    id: 'clinic-laboratory',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.VIEW_LAB_TESTS,
    children: [
      {
        name: 'navigation.clinic.laboratory.tests',
        id: 'clinic-laboratory-tests',
        href: '/clinic/laboratory/tests',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_LAB_TESTS,
      },
    ],
  },
  {
    name: 'navigation.clinic.radiology.title',
    id: 'clinic-radiology',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.VIEW_RADIOLOGY,
    children: [
      {
        name: 'navigation.clinic.radiology.tests',
        id: 'clinic-radiology',
        href: '/clinic/radiology',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY,
      },
    ],
  },
  {
    name: 'navigation.clinic.pharmacy.title',
    id: 'clinic-pharmacy',
    icon: HeartIcon,
    permission: PermissionKeys.VIEW_PRESCRIPTIONS,
    children: [
      {
        name: 'navigation.clinic.pharmacy.prescriptions',
        id: 'clinic-pharmacy-prescriptions',
        href: '/clinic/pharmacy/prescriptions',
        icon: DocumentTextIcon,
        permission: PermissionKeys.VIEW_PRESCRIPTIONS,
      },
    ],
  },
  {
    name: 'navigation.clinic.financial.title',
    id: 'clinic-financial',
    icon: BanknotesIcon,
    permission: PermissionKeys.VIEW_FINANCIALS,
    children: [
      {
        name: 'navigation.clinic.financial.dashboard',
        id: 'clinic-financial-dashboard',
        href: '/clinic/financial',
        icon: CurrencyDollarIcon,
        permission: PermissionKeys.ACCESS_CLINIC_DASHBOARD,
      },
      {
        name: 'navigation.clinic.financial.servicePrices',
        id: 'clinic-financial-service-prices',
        href: '/clinic/financial/service-prices',
        icon: CurrencyDollarIcon,
        permission: PermissionKeys.MANAGE_SERVICE_PRICES,
      },
      {
        name: 'navigation.clinic.financial.expenses',
        id: 'clinic-financial-expenses',
        href: '/clinic/financial/expenses',
        icon: ReceiptPercentIcon,
        permission: PermissionKeys.VIEW_EXPENSES,
      },
      {
        name: 'navigation.clinic.financial.invoices',
        id: 'clinic-financial-invoices',
        href: '/clinic/financial/invoices',
        icon: DocumentDuplicateIcon,
        permission: PermissionKeys.VIEW_INVOICES,
      },
      {
        name: 'navigation.clinic.financial.revenues',
        id: 'clinic-financial-revenues',
        href: '/clinic/financial/revenues',
        icon: ArrowTrendingUpIcon,
        permission: PermissionKeys.VIEW_REVENUES,
      },
      {
        name: 'navigation.clinic.financial.salaries',
        id: 'clinic-financial-salaries',
        href: '/clinic/financial/salaries',
        icon: UsersIcon,
        permission: PermissionKeys.VIEW_SALARIES,
      },
      {
        name: 'navigation.clinic.financial.transactions',
        id: 'clinic-financial-transactions',
        href: '/clinic/financial/transactions',
        icon: ArrowsRightLeftIcon,
        permission: PermissionKeys.VIEW_TRANSACTIONS,
      },
    ],
  },
  {
    name: 'navigation.clinic.reports.title',
    id: 'clinic-reports',
    icon: ChartBarIcon,
    permission: PermissionKeys.VIEW_REPORTS,
    children: [
      {
        name: 'navigation.clinic.reports.view',
        id: 'clinic-reports-view',
        href: '/clinic/reports',
        icon: ChartBarIcon,
        permission: PermissionKeys.VIEW_REPORTS,
      },
      {
        name: 'navigation.clinic.reports.generate',
        id: 'clinic-reports-generate',
        href: '/clinic/reports/generate',
        icon: DocumentTextIcon,
        permission: PermissionKeys.GENERATE_REPORTS,
      },
    ],
  },
  {
    name: 'navigation.clinic.settings.title',
    id: 'clinic-settings',
    icon: Cog6ToothIcon,
    permission: PermissionKeys.VIEW_CLINIC_SETTINGS,
    children: [
      {
        name: 'navigation.clinic.settings.general',
        id: 'clinic-settings-general',
        href: '/clinic/settings',
        icon: Cog6ToothIcon,
        permission: PermissionKeys.VIEW_CLINIC_SETTINGS,
      },
      {
        name: 'navigation.clinic.settings.profile',
        id: 'clinic-profile',
        href: '/clinic/profile',
        icon: BuildingOfficeIcon,
        permission: PermissionKeys.VIEW_CLINIC_PROFILE,
      },
    ],
  },
];
