import {
  ChartBarIcon,
  UserGroupIcon,
  ClipboardDocumentListIcon,
  CalendarIcon,
  UserIcon,
  HomeIcon,
  ListBulletIcon,
  AcademicCapIcon,
  GlobeAltIcon,
  MapPinIcon,
  BuildingOfficeIcon,
  ArchiveBoxIcon,
  BoltIcon,
  BookmarkIcon,
  HeartIcon,
  PuzzlePieceIcon,
  ShieldCheckIcon,
  DocumentTextIcon,
  ClipboardDocumentCheckIcon,
  SparklesIcon,
  Cog6ToothIcon,
  BanknotesIcon,
  CurrencyDollarIcon,
  ReceiptPercentIcon,
  DocumentDuplicateIcon,
  ArrowTrendingUpIcon,
  UsersIcon,
  ArrowsRightLeftIcon,
} from '@heroicons/react/24/outline';

import type { NavItem } from '@/types/navigation';
import { PermissionKeys } from './permissions';

export const doctorNav: NavItem[] = [
  {
    name: 'Dashboard',
    id: 'doctor-dashboard',
    href: '/doctor/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_DOCTOR_DASHBOARD,
  },
  {
    name: 'Vistis',
    id: 'doctor-visits',
    href: '/doctor/visits',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.MANAGE_VISITS,
  },
  {
    name: 'Leaves',
    id: 'doctor-leaves',
    href: '/doctor/leaves',
    icon: CalendarIcon,
    permission: PermissionKeys.MANAGE_LEAVES,
  },
  {
    name: 'Profile',
    id: 'doctor-profile',
    href: '/doctor/profile',
    icon: UserIcon,
    permission: PermissionKeys.VIEW_PROFILE,
  },
];

export const adminNav: NavItem[] = [
  {
    name: 'Dashboard',
    id: 'admin-dashboard',
    href: '/admin/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_ADMIN_DASHBOARD,
  },
  {
    name: 'Clinics',
    id: 'admin-clinics',
    icon: HomeIcon,
    permission: PermissionKeys.MANAGE_CLINICS,
    children: [
      {
        name: 'Management',
        id: 'admin-clinics-management',
        icon: ClipboardDocumentListIcon,
        permission: PermissionKeys.MANAGE_CLINICS,
        children: [
          {
            name: 'Clinic List',
            id: 'admin-clinics-list',
            href: '/admin/clinics',
            icon: ClipboardDocumentListIcon,
            permission: PermissionKeys.VIEW_CLINICS,
          },
          {
            name: 'Add Clinic',
            id: 'admin-clinics-add',
            href: '/admin/clinics/add',
            icon: UserGroupIcon,
            permission: PermissionKeys.CREATE_CLINICS,
          },
        ],
      },
      {
        name: 'Reports',
        id: 'admin-clinics-reports',
        icon: ChartBarIcon,
        permission: PermissionKeys.VIEW_REPORTS,
        children: [
          {
            name: 'Performance',
            id: 'admin-clinics-reports-performance',
            href: '/admin/clinics/reports/performance',
            icon: ChartBarIcon,
            permission: PermissionKeys.VIEW_PERFORMANCE_REPORTS,
          },
          {
            name: 'Analytics',
            id: 'admin-clinics-reports-analytics',
            href: '/admin/clinics/reports/analytics',
            icon: ChartBarIcon,
            permission: PermissionKeys.VIEW_ANALYTICS_REPORTS,
          },
        ],
      },
    ],
  },
  {
    name: 'Lookups',
    id: 'admin-lookups',
    icon: ListBulletIcon,
    permission: PermissionKeys.MANAGE_LOOKUPS,
    children: [
      {
        name: 'Specialty',
        id: 'admin-lookups-specialty',
        href: '/admin/lookups/specialty',
        icon: AcademicCapIcon,
        permission: PermissionKeys.VIEW_SPECIALTY,
      },
      {
        name: 'Country',
        id: 'admin-lookups-country',
        href: '/admin/lookups/country',
        icon: GlobeAltIcon,
        permission: PermissionKeys.VIEW_COUNTRY,
      },
      {
        name: 'City',
        id: 'admin-lookups-city',
        href: '/admin/lookups/city',
        icon: MapPinIcon,
        permission: PermissionKeys.VIEW_CITY,
      },
      {
        name: 'Clinic Type',
        id: 'admin-lookups-clinic-type',
        href: '/admin/lookups/clinic-type',
        icon: BuildingOfficeIcon,
        permission: PermissionKeys.VIEW_CLINIC_TYPE,
      },
      {
        name: 'Radiology Test Category',
        id: 'admin-lookups-radiology-test-category',
        href: '/admin/lookups/radiology-test-category',
        icon: ArchiveBoxIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY_TEST_CATEGORY,
      },
      {
        name: 'Radiology Test',
        id: 'admin-lookups-radiology-test',
        href: '/admin/lookups/radiology-test',
        icon: BoltIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY_TEST,
      },
      {
        name: 'Medication Type',
        id: 'admin-lookups-medication-type',
        href: '/admin/lookups/medication-type',
        icon: BookmarkIcon,
        permission: PermissionKeys.VIEW_MEDICATION_TYPE,
      },
      {
        name: 'Medicine',
        id: 'admin-lookups-medicine',
        href: '/admin/lookups/medicine',
        icon: HeartIcon,
        permission: PermissionKeys.VIEW_MEDICINE,
      },
      {
        name: 'Lab Test Category',
        id: 'admin-lookups-lab-test-category',
        href: '/admin/lookups/lab-test-category',
        icon: PuzzlePieceIcon,
        permission: PermissionKeys.VIEW_LAB_TEST_CATEGORY,
      },
      {
        name: 'Lab Test',
        id: 'admin-lookups-lab-test',
        href: '/admin/lookups/lab-test',
        icon: ShieldCheckIcon,
        permission: PermissionKeys.VIEW_LAB_TEST,
      },
      {
        name: 'Diagnosis Category',
        id: 'admin-lookups-diagnosis-category',
        href: '/admin/lookups/diagnosis-category',
        icon: DocumentTextIcon,
        permission: PermissionKeys.VIEW_DIAGNOSIS_CATEGORY,
      },
      {
        name: 'Diagnosis',
        id: 'admin-lookups-diagnosis',
        href: '/admin/lookups/diagnosis',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_DIAGNOSIS,
      },
      {
        name: 'Dental Procedure',
        id: 'admin-lookups-dental-procedure',
        href: '/admin/lookups/dental-procedure',
        icon: SparklesIcon,
        permission: PermissionKeys.VIEW_DENTAL_PROCEDURE,
      },
    ],
  },
  {
    name: 'Users',
    id: 'admin-users',
    href: '/admin/users',
    icon: UserGroupIcon,
    permission: PermissionKeys.VIEW_USERS,
  },
];

export const clinicNav: NavItem[] = [
  {
    name: 'Dashboard',
    id: 'clinic-dashboard',
    href: '/clinic/dashboard',
    icon: ChartBarIcon,
    permission: PermissionKeys.ACCESS_CLINIC_DASHBOARD,
  },
  {
    name: 'Appointments',
    id: 'clinic-appointments',
    href: '/clinic/appointments',
    icon: CalendarIcon,
    permission: PermissionKeys.VIEW_APPOINTMENTS,
  },
  {
    name: 'Patients',
    id: 'clinic-patients',
    href: '/clinic/patients',
    icon: UserGroupIcon,
    permission: PermissionKeys.VIEW_PATIENTS,
  },

  {
    name: 'Staff',
    id: 'clinic-staff',
    icon: UserIcon,
    permission: PermissionKeys.VIEW_STAFF,
    children: [
      {
        name: 'Staff List',
        id: 'clinic-staff-list',
        href: '/clinic/staff',
        icon: UserGroupIcon,
        permission: PermissionKeys.VIEW_STAFF,
      },
      {
        name: 'Leaves',
        id: 'clinic-staff-leaves',
        href: '/clinic/staff/leaves',
        icon: CalendarIcon,
        permission: PermissionKeys.MANAGE_LEAVES,
      },
    ],
  },
  {
    name: 'Laboratory',
    id: 'clinic-laboratory',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.VIEW_LAB_TESTS,
    children: [
      {
        name: 'Tests',
        id: 'clinic-laboratory-tests',
        href: '/clinic/laboratory/tests',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_LAB_TESTS,
      },
    ],
  },

  {
    name: 'Radiology',
    id: 'clinic-radiology',
    icon: ClipboardDocumentListIcon,
    permission: PermissionKeys.VIEW_RADIOLOGY,
    children: [
      {
        name: 'Tests',
        id: 'clinic-radiology',
        href: '/clinic/radiology',
        icon: ClipboardDocumentCheckIcon,
        permission: PermissionKeys.VIEW_RADIOLOGY,
      },
    ],
  },
  {
    name: 'Pharmacy',
    id: 'clinic-pharmacy',
    icon: HeartIcon,
    permission: PermissionKeys.VIEW_PRESCRIPTIONS,
    children: [
      {
        name: 'Prescriptions',
        id: 'clinic-pharmacy-prescriptions',
        href: '/clinic/pharmacy/prescriptions',
        icon: DocumentTextIcon,
        permission: PermissionKeys.VIEW_PRESCRIPTIONS,
      },
    ],
  },
  {
    name: 'Financial',
    id: 'clinic-financial',
    icon: BanknotesIcon,
    permission: PermissionKeys.VIEW_FINANCIALS,
    children: [
      {
        name: 'Financial Dashboard ',
        id: 'clinic-financial-dashboard',
        href: '/clinic/financial',
        icon: CurrencyDollarIcon,
        permission: PermissionKeys.ACCESS_CLINIC_DASHBOARD,
      },
      {
        name: 'Service Prices',
        id: 'clinic-financial-service-prices',
        href: '/clinic/financial/service-prices',
        icon: CurrencyDollarIcon,
        permission: PermissionKeys.MANAGE_SERVICE_PRICES,
      },
      {
        name: 'Expenses',
        id: 'clinic-financial-expenses',
        href: '/clinic/financial/expenses',
        icon: ReceiptPercentIcon,
        permission: PermissionKeys.VIEW_EXPENSES,
      },
      {
        name: 'Invoices',
        id: 'clinic-financial-invoices',
        href: '/clinic/financial/invoices',
        icon: DocumentDuplicateIcon,
        permission: PermissionKeys.VIEW_INVOICES,
      },
      {
        name: 'Revenues',
        id: 'clinic-financial-revenues',
        href: '/clinic/financial/revenues',
        icon: ArrowTrendingUpIcon,
        permission: PermissionKeys.VIEW_REVENUES,
      },
      {
        name: 'Salaries',
        id: 'clinic-financial-salaries',
        href: '/clinic/financial/salaries',
        icon: UsersIcon,
        permission: PermissionKeys.VIEW_SALARIES,
      },
      {
        name: 'Transactions',
        id: 'clinic-financial-transactions',
        href: '/clinic/financial/transactions',
        icon: ArrowsRightLeftIcon,
        permission: PermissionKeys.VIEW_TRANSACTIONS,
      },
    ],
  },
  {
    name: 'Reports',
    id: 'clinic-reports',
    icon: ChartBarIcon,
    permission: PermissionKeys.VIEW_REPORTS,
    children: [
      {
        name: 'View Reports',
        id: 'clinic-reports-view',
        href: '/clinic/reports',
        icon: ChartBarIcon,
        permission: PermissionKeys.VIEW_REPORTS,
      },
      {
        name: 'Generate Reports',
        id: 'clinic-reports-generate',
        href: '/clinic/reports/generate',
        icon: DocumentTextIcon,
        permission: PermissionKeys.GENERATE_REPORTS,
      },
    ],
  },
  {
    name: 'Settings',
    id: 'clinic-settings',
    href: '/clinic/settings',
    icon: Cog6ToothIcon,
    permission: PermissionKeys.VIEW_CLINIC_SETTINGS,
  },
];
